---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "gateway"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "gateway"
  namespace: "steve-overflow"
  labels:
    app: "gateway"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "gateway"
  template:
    metadata:
      labels:
        app: "gateway"
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: gateway-config
          name: "gateway-sha256-1"
          image: "gcr.io/steveoverflow-289df/gateway:latest"
          imagePullPolicy: Always
          resources:
          limits:
            cpu: "0.05"

---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "post-service-hpa-yrnk"
  namespace: "steve-overflow"
  labels:
    app: "post-service"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "post-service"
    apiVersion: "apps/v1"
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 25
