# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build and Deploy to GKE

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: steveoverflow-289df 
  GKE_CLUSTER: cluster-overflow    # Add your cluster name here.
  GKE_ZONE: europe-west1-b    # Add your cluster zone here.
  DEPLOYMENT_NAME: gateway # Add your deployment name here.
  IMAGE: gateway

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: steveoverflow-289df

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "gcr.io/steveoverflow-289df/gateway:latest" \
          --build-arg GITHUB_SHA="latest" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "gcr.io/steveoverflow-289df/gateway:latest"

    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/steveoverflow-289df/gateway:latest
        ./kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/gateway --namespace steve-overflow
        kubectl get services -o wide --namespace steve-overflow


# name: PostService

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     name: Go Build
#     runs-on: ubuntu-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
#     steps:
#     - uses: actions/checkout@v3

#     - name: Set up Go
#       uses: actions/setup-go@v3
#       with:
#         go-version: 1.19.2

#     - name: Build
#       run: go build -v ./...

#   push:
#     name: Push new container to registry
#     runs-on: ubuntu-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
#     needs: build
#     steps:
#       - uses: actions/checkout@v3

#       - uses: docker/login-action@v2
#         with:
#           username: stevenjansen
#           password: dckr_pat_mNcohwOkR1oF0fYkDv7ZHzO86Rs

#       - name: Build and push image to registry
#         id: build-image
#         run: |
#           docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t stevenjansen/steveoverflow:postservice --label dockerfile-path=Dockerfile
#           docker push stevenjansen/steveoverflow:postservice

